name: Update SQL Server 2022 database

#Sets the trigger to update when update is pushed to a sql-action-v1-feature branch
on:
  push:
    branches: 
      - main

jobs:

  # Job to build and publish the dacpac
  BuildDacpac:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.3.0
      # Build dacpac using dotnet build
      - name: Build Database project
        run: |
          dotnet build
      # Publish artifact
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: SQLDB
          path: ${{ github.workspace }}/bin/Debug/ 

# Deploy dacpac job
  DeploySQL2022Updates:
    # Set the dependency for the build job
    needs: BuildDacpac
    # Easier to use Github-hosted runner if updating in GitHub
    runs-on: self-hosted

    # Steps to deploy the updates to a SQL Server 2022 Database
    steps:
      - name: download artifact containing dacpac
        # Dowloads Data artifact to dacpac folder
        uses: actions/download-artifact@v3.0.2
        with:
          name: SQLDB
                    
      # Installs dacpac
      # For this to work you MUST have two secrets specified, defaults in my repo are blank
      # One called SQLDB_SERVER which contains your logical SQL Server name
      # Requires a secret SQLDB_CONNECTION_STRING which contains connection string to your SQL Server 2022 database
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1.3
        with:
          # The logical SQL Server name
          server-name: '${{ secrets.SQLDB_SERVER }}'
          # The connection string, including authentication information, for the Azure SQL Database.
          connection-string: '${{ secrets.SQLDB_CONNECTION_STRING }}'
          # Name of the dacpac file in the artifact
          dacpac-package: 'GitHub-SQLServer2022-SDK-DBProject.dacpac'

